#!/bin/sh -e

# Copyright (C) 2012,2013  Henrik Nordstrom <henrik@henriknordstrom.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

pio_to_sram=0x2000
sram_to_pio=0x2004

if [ -f fel-pio.bin ]; then
	./fel write 0x2000 fel-pio.bin
else
	./fel write 0x2000 bin/fel-pio.bin
fi

./fel exec $pio_to_sram
./fel read 0x3000 0x228 pio.reg
./pio -i pio.reg print > pio.old
cat pio.old | fgrep -v '<0><0><0><0>'

while read cmd; do
	./pio -i pio.reg -o pio.reg $cmd
	./fel write 0x3000 pio.reg
	./fel exe 0x2004
	./fel exe 0x2000
	./fel read 0x3000 0x228 pio.reg
	./pio -i pio.reg print > pio.new
	diff -U0 pio.old pio.new || true
	mv -f pio.new pio.old
done
