#!/bin/sh -e

# Copyright (C) 2013  Henrik Nordstrom <henrik@henriknordstrom.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

top=`dirname $0`
if [ $# -lt 2 ]; then
	echo "Usage: $0 u-boot-spl.bin u-boot.bin [boot.scr] [kernel script.bin [initramfs]]"
	exit 1
fi
board=$1; shift || (echo "ERROR: u-boot-spl.bin must be specified"; exit 1;)
uboot=$1; shift || (echo "ERROR: u-boot.bin must be specified"; exit 1;)
bootscr=$top/felboot/ramboot.scr
if [ ! -f $bootscr ]; then
	bootscr=$top/bin/ramboot.scr
fi
case "$1" in
*.scr)	bootscr="$1"; shift
	;;
esac
if [ $# -ge 1 ]; then
	kernel=$1; shift || true
fi
if [ $# -ge 1 ]; then
	scriptbin=$1; shift || true
fi
if [ $# -ge 1 ]; then
	initramfs=$1; shift || true
fi
fel() {
	echo fel "$@"
	$top/fel $@
}
case $board in
*/*)	felboot=$board
	;;
*)
	felboot=$top/felboot/fel-boot-${board}.bin
	if [ ! -f $felboot ]; then
		felboot=$top/bin/fel-boot-${board}.bin
	fi
	;;
esac
if [ ! -f $felboot ]; then
	echo "ERROR: Can't find SPL FEL binary ${board}"
	exit 1
fi
if [ `wc -c $felboot | cut '-d ' -f1` -gt 15616 ]; then
	echo "ERROR: SPL FEL binary too large. Must be the FEL version of SPL"
	exit 1
fi
if [ ! -f $bootscr ]; then
	echo "ERROR: Can't find boot script '${bootscr}'"
	exit 1
fi
fel write 0x2000 $felboot
fel exe 0x2000
sleep 1 # Wait for DRAM initialization to complete
if [ -n "$uboot" ]; then
	fel write 0x4a000000 $uboot
fi
if [ -n "$bootscr" ]; then
	fel write 0x41000000 $bootscr
fi
if [ -n "$kernel" ]; then
 if [ -n "$scriptbin" ]; then
  fel write 0x43000000 $scriptbin
 fi
 fel write 0x44000000 $kernel
 if [ -n "$initramfs" ]; then
  fel write 0x4c000000 $initramfs
 fi
fi
fel exe 0x4a000000
